accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name="login"),
    # path('logout/', views.logout, name="logout"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.signup, name="signup"),
]

cal/urls.py
from django.urls import re_path, path
from . import views

app_name = 'cal'
urlpatterns = [
    re_path(r'^index/$', views.index, name='index'),
    re_path(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    # re_path('', views.CalendarView.as_view(), name='calendar'),
    re_path(r'^list/$', views.list_sc, name='list'),
    # re_path(r'^event/new/$', views.event, name='event_new'),
	# re_path(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    re_path(r'^event_mem/new/$', views.event_mem, name='event_mem_new'),
    re_path(r'^event_mem/edit/(?P<event_id>\d+)/$', views.CalendarView2.as_view(), name='event_mem_edit'),
    re_path(r'^delete/(?P<pk>[0-9]+)/$', views.delete_post, name='delete_post'),
    re_path(r'^delete_sc/$', views.delete_schedule, name='delete_schedule'),
    re_path(r'^schedule/$', views.schedule, name='schedule'),
    re_path(r'^schedule_add/$', views.schedule_add, name='schedule_add'),
    re_path(r'^schedule/edit/(?P<event_id>\d+)/$', views.schedule_edit, name='schedule_edit'),
    re_path(r'^option/$', views.option, name='option'),
    path('', views.main, name='main'),
]

djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cal/models.py
from django.db import models
from django.urls import reverse

class Event(models.Model):
    name = models.CharField(max_length=200)
    time = models.DateTimeField(null=True, blank=True)
    count = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    name_id = models.CharField(max_length=200, null=True, blank=True)
    account = models.CharField(max_length=200)
    cancel = models.CharField(max_length=2, null=True, blank=True)  # 스케쥴 취소
    cancel_comment = models.TextField(null=True, blank=True)  # 희망 운동시간
    # loop = models.CharField(max_length=200, null=True, blank=True)  # 일정 반복기능
    # start_time = models.DateTimeField()
    # end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('accounts:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.name} </a>'

class Mem(models.Model):
    name = models.CharField(max_length=200, null=True)  # 회원 이름
    phone = models.CharField(max_length=200, null=True, blank=True)  # 폰 번호
    start_date = models.DateField(null=True, blank=True)  # 시작일
    end_date = models.DateField(null=True, blank=True)  # 종료일
    count = models.CharField(max_length=200, blank=True, null=True)  # pt횟수

    food_CHOICES = (
        ('', ''),
        ('o', 'o'),
        ('x', 'x'),
    )
    food = models.CharField(max_length=3, blank=True, choices=food_CHOICES, default='')  # 식단진행
    job = models.CharField(max_length=200, null=True, blank=True)  # 직업
    residence = models.CharField(max_length=200, null=True, blank=True)  # 거주
    stature = models.PositiveIntegerField(blank=True, null=True)  # 키
    age = models.PositiveIntegerField(blank=True, null=True)  # 나이
    weight = models.CharField(max_length=200, null=True, blank=True)  # 체중
    muscle = models.CharField(max_length=200, null=True, blank=True)  # 골격근량
    fat = models.CharField(max_length=200, null=True, blank=True)  # 체지방률
    date = models.CharField(max_length=200, null=True, blank=True)  # 체중/골격근량/체지방률 날짜
    hope_time = models.CharField(max_length=200, null=True, blank=True)  # 희망 운동시간
    health_career = models.TextField(null=True, blank=True)  # 운동경력
    note1 = models.TextField(null=True, blank=True)  # 특이사항 및 병력
    note2 = models.TextField(null=True, blank=True)  # 운동목적 및 방향
    account = models.CharField(max_length=200, null=True)  # 로그인 계정 구분
    membership_start_date = models.DateField(null=True, blank=True)  # 회원권 시작일
    membership_end_date = models.DateField(null=True, blank=True)  # 회원권 종료일
    health_start_date = models.DateField(null=True, blank=True)  # 헬스 시작일
    health_end_date = models.DateField(null=True, blank=True)  # 헬스 종료일
    class_start_date = models.DateField(null=True, blank=True)  # 수업 시작일
    class_end_date = models.DateField(null=True, blank=True)  # 수업 종료(예상)일

    resist_CHOICES = (
        ('', ''),
        ('워크인', '워크인'),
        ('재등록', '재등록'),
        ('SNS', 'SNS'),
        ('OT', 'OT'),
        ('인계', '인계'),
    )
    resist_category = models.CharField(max_length=3, choices=resist_CHOICES, blank=True, default='')  # 등록 구분(초이스필드) -워크인,재등록,SNS,OT

    payment_CHOICES = (
        ('', ''),
        ('카드', '카드'),
        ('현금', '현금'),
        ('이체', '이체'),
    )
    payment = models.CharField(max_length=2, choices=payment_CHOICES, blank=True, default='')  # 결제 방식(초이스필드)
    empty1 = models.BooleanField(default=False)  # 비고칸
    empty2 = models.BooleanField(default=False)  # 비고칸
    empty3 = models.BooleanField(default=False)  # 비고칸
    empty4 = models.BooleanField(default=False)  # 비고칸
    empty5 = models.BooleanField(default=False)  # 비고칸
    alarm = models.TextField(null=True, blank=True)  # 알림칸
    alarm_check = models.BooleanField(default=False)  # 비고칸
    # photo = models.FileField(upload_to = 'uploads/', null=True)
    money = models.PositiveIntegerField(blank=True, null=True)  # 금액
    re_data = models.TextField(blank=True)  # 재 등록시 과거 데이터 저장
    start_count = models.PositiveIntegerField(blank=True, null=True)  # 시작 카운트

    @property
    def get_html_url(self):
        url = reverse('accounts:event_mem_edit', args=(self.id,))
        return f'<a href="{url}"> {self.name} </a>'

class Option(models.Model):
    account = models.CharField(max_length=200, null=True, blank=True)  # 로그인 계정 구분
    count = models.CharField(max_length=200, null=True, blank=True)  # 비고칸
    empty1 = models.CharField(max_length=200, null=True, blank=True)  # 비고칸
    empty2 = models.CharField(max_length=200, null=True, blank=True)  # 비고칸
    empty3 = models.CharField(max_length=200, null=True, blank=True)  # 비고칸
    empty4 = models.CharField(max_length=200, null=True, blank=True)  # 비고칸
    empty5 = models.CharField(max_length=200, null=True, blank=True)  # 비고칸
    count_money = models.TextField(blank=True)  # 횟수에 따른 금액 변화 설정
    end_alarm_cb = models.BooleanField(default=False)  # 헬스 종료일 알림 체크박스
    end_alarm = models.PositiveIntegerField(blank=True, null=True)  # 헬스 종료일 알림 내용

    @property
    def get_html_url(self):
        url = reverse('accounts:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.name} </a>'


# python manage.py createsuperuser
# python manage.py makemigrations
# python manage.py migrate
# python manage.py runserver
# python manage.py runserver 0.0.0.0:8080

# git add .
# git commit -m "message"
# git push -u origin master

cal/views.py
from datetime import datetime, timedelta, date
from datetime import time as date_time
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.views.generic.edit import ModelFormMixin
from django.urls import reverse, resolve
from django.utils.safestring import mark_safe
import calendar
import json
from django.contrib.auth import authenticate, login
import time

from .models import *
from .utils import Calendar, Calendar2
from .forms import EventForm, MemForm, OptionForm

def index(request):
    return HttpResponse('hello')

def list_sc(request):
    # return HttpResponse(reverse('cal:list'))

    # name_list = Mem.objects.order_by('-name')
    # print(name_list)
    # return render(request, 'cal/list.html')
    user_name = request.user.username

    name_list = Mem.objects.filter(account=user_name)
    # name_list = Mem.objects.order_by('-name')
    context = {'name_list': name_list,}
    return render(request, 'cal/list.html', context)

class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        user_name = self.request.user.username
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        cal.setfirstweekday(calendar.SUNDAY)
        html_cal = cal.formatmonth(user_name, withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)

        op = Option.objects.filter(account=user_name).values()[0]
        if op['end_alarm'] != None:
            al = [str(op['end_alarm_cb']), op['end_alarm']]
        else:
            al = [str(op['end_alarm_cb']), '']

        user_list = list(Mem.objects.filter(account=user_name).values_list('name','health_end_date'))
        check_list = []
        for ul in user_list:
            if ul[1] != None:
                now = datetime.now()
                diff = datetime.combine(ul[1], date_time()) - now
                check_list.append([ul[0], diff.days+1])

        context['al'] = al
        context['user_list'] = check_list
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)

    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

# def event(request, event_id=None):
#     name = request.GET.get('name')
#     print(name)
#     if event_id:
#         instance = get_object_or_404(Event, pk=event_id)
#     else:
#         instance = Event()
#
#     form = EventForm(request.POST or None, instance=instance, initial={'choice': [(name, name)]})
#     if request.POST and form.is_valid():
#         form.save()
#         return HttpResponseRedirect(reverse('cal:calendar'))
#     return render(request, 'cal/event.html', {'form': form})

class CalendarView2(generic.ListView, ModelFormMixin):
    model = Event
    template_name = 'cal/event_mem.html'

    form_class = MemForm

    def get(self, request, *args, **kwargs):
        user_name = self.request.user.username
        self.object = None
        if kwargs != {}:
            self.id = kwargs['event_id']
            instance = get_object_or_404(Mem, pk=self.id)
        else:
            instance = Mem()

        self.form = MemForm(instance=instance, initial={'account': user_name})

        return generic.ListView.get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = None
        # self.form = self.get_form(self.form_class)
        if kwargs != {}:
            self.id = kwargs['event_id']
            instance = get_object_or_404(Mem, pk=self.id)
        else:
            instance = Mem()

        jsonDec = json.decoder.JSONDecoder()
        user_name = self.request.user.username

        if instance.weight != None:
            weight = jsonDec.decode(instance.weight)
            self.weight = [float(i) for i in weight]
            muscle = jsonDec.decode(instance.muscle)
            self.muscle = [float(i) for i in muscle]
            fat = jsonDec.decode(instance.fat)
            self.fat = [float(i) for i in fat]
            self.date = jsonDec.decode(instance.date)
        else:
            self.weight = []
            self.muscle = []
            self.fat = []
            self.date = []

        if instance.re_data != '':
            self.re_data = jsonDec.decode(instance.re_data)
        else:
            self.re_data = []

        # 횟수당 금액 불러오는곳
        if len(Option.objects.filter(account=user_name)) != 0:
            op_id = Option.objects.filter(account=user_name).values_list('id', flat=True)[0]
            op_instance = Option.objects.get(pk=op_id)

            option = Option.objects.filter(account=user_name).values()
            if len(option) != 0:
                if option[0]['count'] == 'NaN':
                    option[0]['count'] = 0
                self.option_ = [option[0]['count'], option[0]['empty1'], option[0]['empty2'], option[0]['empty3'],
                                option[0]['empty4'], option[0]['empty5']]
            else:
                self.option_ = ['0', None, None, None, None, None]
        else:
            op_instance = Option()
            self.option_ = ['0', None, None, None, None, None]

        if op_instance.count_money != '':
            self.count = jsonDec.decode(op_instance.count_money)
        else:
            self.count = [['', '', '', '', ''], ['', '', '', '', '']]

        self.alarm_ = instance.alarm_check
        self.alarm_text = instance.alarm

        self.form = MemForm(self.request.POST or None, instance=instance, initial={'account': user_name})

        if self.form.is_valid() and request.method == 'POST':
            wei_list = []
            mus_list = []
            fat_list = []
            date_list = []
            i = 0
            while True:
                if request.POST.get(f'wei_{i}') == None:
                    break
                if request.POST.get(f'wei_{i}') != '' and request.POST.get(f'mus_{i}') != '' and request.POST.get(f'fat_{i}') != '' and request.POST.get(f'date_{i}') != '':
                    wei_list.append(request.POST.get(f'wei_{i}'))
                    mus_list.append(request.POST.get(f'mus_{i}'))
                    fat_list.append(request.POST.get(f'fat_{i}'))
                    date_list.append(request.POST.get(f'date_{i}'))
                i += 1
            self.weight = [float(i) for i in wei_list]
            self.muscle = [float(i) for i in mus_list]
            self.fat = [float(i) for i in fat_list]
            self.date = date_list

            if instance.re_data != '':
                self.re_data = jsonDec.decode(instance.re_data)
            else:
                self.re_data = []

            wei_list = json.dumps(wei_list)
            mus_list = json.dumps(mus_list)
            fat_list = json.dumps(fat_list)
            date_list = json.dumps(date_list)

            self.object = self.form.save(commit=False)
            self.object.weight = wei_list
            self.object.muscle = mus_list
            self.object.fat = fat_list
            self.object.date = date_list
            self.object.save()

            op_instance.account = user_name
            op_instance.count = request.POST.get('empty_count')
            op_instance.empty1 = request.POST.get('empty1_t')
            op_instance.empty2 = request.POST.get('empty2_t')
            op_instance.empty3 = request.POST.get('empty3_t')
            op_instance.empty4 = request.POST.get('empty4_t')
            op_instance.empty5 = request.POST.get('empty5_t')
            op_instance.save()

            if len(Option.objects.filter(account=user_name)) != 0:
                option = Option.objects.filter(account=user_name).values()
                if len(option) != 0:
                    if option[0]['count'] == 'NaN':
                        option[0]['count'] = 0
                    self.option_ = [option[0]['count'], option[0]['empty1'], option[0]['empty2'], option[0]['empty3'],
                                    option[0]['empty4'], option[0]['empty5']]
                else:
                    self.option_ = ['0', None, None, None, None, None]
            else:
                self.option_ = ['0', None, None, None, None, None]

        return self.get(request, *args, **kwargs)
        # return generic.ListView.get(self, request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user_name = self.request.user.username
        context = super(CalendarView2, self).get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar2(d.year, d.month, self.id)
        cal.setfirstweekday(calendar.SUNDAY)
        html_cal = cal.formatmonth(user_name, withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month2'] = prev_month2(d)
        context['next_month2'] = next_month2(d)
        context['form'] = self.form
        context['id'] = self.id
        context['weight_data'] = self.weight
        context['muscle_data'] = self.muscle
        context['fat_data'] = self.fat
        context['wmf_date'] = self.date
        context['empty'] = self.option_
        context['alarm_'] = self.alarm_
        context['alarm_text'] = self.alarm_text
        context['re_data'] = self.re_data
        context['count_money'] = self.count

cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1.0, user-scalable=0">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}?after">
  <script src="{% static 'bootstrap.min.js' %}"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.css"/>
  <script src="https://d3js.org/d3.v3.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js"></script>
  <title>회원 관리</title>
</head>
<body>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  <hr style="margin:auto;">
  <!-- 네비게이션바 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <div class="container-fluid">
            {% if not user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'cal:main' %}">메인</a>
            {% else %}
                <a class="navbar-brand" href="{% url 'cal:calendar' %}">{{ user.username }}</a>
            {% endif %}
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="/accounts/login">로그인</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/accounts/signup">회원가입</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cal:option' %}">옵션</a>
                        </li>
                        <li class="nav-item">
                            {% csrf_token %}
                            <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
  {% if not user.is_authenticated %}
    <div style="width: 100%; margin-left: auto; margin-right: auto; margin-top:100px;">
        <label style="font-size: 20px; text-align: center;width: 100%;">로그인 후 사용해 주세요.</label>
    </div>
<!--    <div class="login_form">-->
<!--      <div class="login_btn">-->
<!--        <a class="btn btn-info" href = '/accounts/login' style="width: 100px;">로그인</a>-->
<!--      </div>-->
<!--      <div class="login_btn">-->
<!--        <a class="btn btn-info" href = '/accounts/signup' style="width: 100px;">회원가입</a>-->
<!--      </div>-->
<!--    </div>-->
  {% else %}
    {% block content %}
    {% endblock %}
  {% endif %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script>
    $('ul.select li').click(function(e){
      var item = $(e.target);
      item.addClass('selected');
      item.siblings().removeClass('selected');

      var list = new Array();
      $("input[name=sc_time]").each(function(index, item2){
         list.push($(item2).val(item.text()));
      });
      time_select(e.target.textContent);

<!--      $('#events').val(item.text());-->
    });
  </script>

  {% block script %}
  {% endblock %}
</body>
</html>

cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}
<!--달력-->
{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> < </a>
<!--	<form method="POST" action="{% url 'accounts:logout' %}">-->
<!--		{% csrf_token %}-->
<!--		<a class="btn btn-info left" style="margin-left: 30px" >{{ user.username }}</a>-->
<!--		<input class="btn btn-info left" type="submit" value="로그아웃">-->
<!--	</form>-->
	<a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> > </a>
	<a class="btn btn-info right" href="{% url 'cal:list' %}"> 회원 목록 </a>
	<a class="btn btn-info right" href=""> 현황표 </a>
</div>
<div id="alarm_box" class="alarm_box" hidden><button onclick="alarm_box_close();" id="alarm_btn"></button></div>
<script>
    function alarm_box_close() {
        document.getElementById('alarm_box').hidden = true;
    }

    var al = '{{ al }}';
	al = JSON.parse(al.replace(/&#x27;/g, '"'));
	if(al[0] != 'False'){
		if(al[1] != ''){
			var text = '';
			var user_list = '{{ user_list }}';
			user_list = JSON.parse(user_list.replace(/&#x27;/g, '"'));
			if(user_list.length != 0){
				for (let i = 0; i < user_list.length; i++){
					if(al[1] > user_list[i][1] && -1 < user_list[i][1]){
						text += '' + user_list[i][0] + ' 헬스 종료 ' + user_list[i][1] + ' 일 전\n'
						document.getElementById('alarm_box').hidden = false;
					}
				}
			}
			document.getElementById('alarm_btn').innerText = text;
			console.log(text);
		}
	}
</script>
{{ calendar }}
{% endblock %}

cal/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
<!--회원 추가-->
{% endblock %}

{% block content %}
<div class="clearfix">
<!--  <a class="btn btn-info left" href="{% url 'accounts:event_mem_new' %}"> < </a>-->
    <input class="btn btn-info left" type="button" value="<<" onclick="history.back();" />
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> 확인 </button></td></tr>
  </table>
</form>
{% endblock %}

cal/templates/cal/list.html
{% extends 'cal/base.html' %}

{% block title %}
<!--회원 목록-->
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> 달력 </a>
  <a class="btn btn-info right" href="{% url 'cal:event_mem_new'%}"> 회원 추가 </a>
</div>


<table style="margin: auto;">
    {% for na_me in name_list %}
        <tr>
            <td width="95%" height="100px">
                <div style="margin-top: 15px;margin-left: 7px;margin-right: 7px;">
                    <form action="{% url 'cal:event_mem_edit' na_me.id %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-info mem_list" type="submit" value="{{ na_me.name }}">
                    </form>
                </div>
            </td>
            <td height="100px">
                <div style="margin-top: 15px;margin-right: 7px;">
                    <form action="{% url 'cal:delete_post' na_me.id %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-info mem_list" type="submit" value="삭제">
                    </form>
                </div>
            </td>
        </tr>
    {% endfor %}
</table>
<!--        <a class="btn btn-info mem_list" href="/event_mem/edit/{{ na_me.id }}/"> {{ na_me.name }} </a>-->

{% endblock %}

cal/templates/cal/main.html
{% extends 'cal/base.html' %}
{% block content %}
<div class="login_form">
  <div>
    <a class="btn btn-info" href = '/accounts/login' style="width: 100px;">로그인</a>
  </div>
  <div>
    <a class="btn btn-info" href = '/accounts/signup' style="width: 100px;">회원가입</a>
  </div>
</div>
{% endblock %}